[package]
name = "rage"
description = "[BETA] A simple, secure, and modern encryption tool."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "../README.md"
keywords = ["age", "cli", "encryption"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "rage"

[package.metadata.deb]
name = "rage"
extended-description = """\
age is a simple, secure and modern encryption format with small explicit keys, \
no config options, and UNIX-style composability. rage is a Rust implementation \
of the age specification."""
section = "utils"
assets = [
    ["target/release/rage", "usr/bin/", "755"],
    ["target/release/rage-keygen", "usr/bin/", "755"],
    ["target/release/rage-mount", "usr/bin/", "755"],
    ["../target/rage.1.gz", "usr/share/man/man1/", "644"],
    ["../target/rage-keygen.1.gz", "usr/share/man/man1/", "644"],
    ["../target/rage-mount.1.gz", "usr/share/man/man1/", "644"],
    ["../README.md", "usr/share/doc/rage/README.md", "644"],
]
features = ["mount"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
# rage and rage-keygen dependencies
age = { version = "0.2.0", path = "../age", features = ["cli-common"] }
chrono = "0.4"
console = "0.9"
env_logger = "0.7"
gumdrop = "0.7"
log = "0.4"
minreq = { version = "2", features = ["https"] }
pinentry = "0.1"
secrecy = "0.6"

# rage-mount dependencies
fuse_mt = { version = "0.5", optional = true }
libc = { version = "0.2", optional = true }
tar = { version = "0.4", optional = true }
time = { version = "0.1", optional = true }
zip = { version = "0.5", optional = true }

# YubiKey dependencies
dialoguer = { version = "0.4", optional = true }
hex = { version = "0.4", optional = true }
rand = { version = "0.7", optional = true }
yubikey-piv = { version = "0.0.3", features = ["untested"], optional = true }

[dev-dependencies]
flate2 = "1"
man = "0.3"

[features]
mount = ["fuse_mt", "libc", "tar", "time", "zip"]
unstable = ["age/unstable"]
yubikey = ["age/yubikey", "dialoguer", "hex", "rand", "yubikey-piv"]

[[bin]]
name = "rage-mount"
required-features = ["mount"]
